sound/you2/dooropn.wav
sound/you2/gaceogut.wav
models/player/guerilla/guerilla.mdl
sound/you2/gacemtrdoor.wav
sound/you2/gacemtrdonotqct.wav
sound/you2/psds.wav
sound/you2/nextdr.wav
sound/you2/toarrive.wav
sound/you2/nextshootout.wav
sound/you2/nextglass.wav
sound/jb_snow/music_1.wav
sound/jb_snow/music_2.wav
sound/jb_snow/music_4.wav
sound/jb_snow/music_5.wav
sound/jb_snow/music_3.wav
sprites/laserbeam.spr
models/player/gsg9/gsg9.mdl
sound/you2/nextbus.wav
sound/you2/mindthegap.wav
sound/you2/you2gogut.wav
sound/you2/spin.wav
sound/you2/click.wav
sound/you2/shot.wav
sound/you2/you2music02.wav
sound/you2/you2music03.wav
sound/you2/you2music01.wav
sound/you2/you2music04.wav
sound/you2/you2music05.wav
